const PIECES={r:'♜',n:'♞',b:'♝',q:'♛',k:'♚',p:'♟',R:'♜',N:'♞',B:'♝',Q:'♛',K:'♚',P:'♟'};
const START=[['r','n','b','q','k','b','n','r'],Array(8).fill('p'),...Array(4).fill(null).map(()=>Array(8).fill('')),Array(8).fill('P'),['R','N','B','Q','K','B','N','R']];
let state=JSON.parse(localStorage.getItem('lilouChess')||'null')||{coins:30,xp:0,skill:0,heart:3,owned:['starter'],items:[],games:0};
let board=START.map(r=>r.map(x=>x||null)), selected=null, history=[], turn='white', over=false, aiThinking=false, lastMove=null;
const $=id=>document.getElementById(id);
const save=()=>localStorage.setItem('lilouChess',JSON.stringify(state));
function renderStats(){['coins','xp'].forEach(k=>$(k).textContent=state[k]);$('level').textContent=Math.floor(state.skill/100)+1;$('shopCoins').textContent=state.coins;let p=state.skill%100;$('skillbar').style.width=Math.max(5,p)+'%';let names=['Anfänger','Entdecker','Taktik-Fan','Schach-Profi','Meister'];$('skill').textContent=names[Math.min(names.length-1,Math.floor(state.skill/100))];$('difficultyText').textContent='Lilou spielt jetzt auf Stufe '+(Math.min(4,Math.floor(state.skill/100)+1))+'. Je mehr du lernst, desto cleverer wird dein Gegner!';$('hearts').textContent='♥ '.repeat(state.heart).trim()+' ♡ '.repeat(3-state.heart).trim();$('friendMood').textContent=state.heart>=3?'Lilous Freund freut sich!':state.heart===2?'Lilous Freund könnte einen Snack gebrauchen.':'Zeit für eine kleine Pause und etwas Wasser!'}
function color(p){return p&&p===p.toUpperCase()?'white':'black'} function inside(r,c){return r>=0&&r<8&&c>=0&&c<8}
function clone(b){return b.map(r=>r.slice())}
function pseudoMoves(b,r,c,attackOnly=false){let p=b[r][c];if(!p)return[];let col=color(p),type=p.toLowerCase(),out=[];const add=(rr,cc)=>{if(!inside(rr,cc))return false;let t=b[rr][cc];if(!t){out.push([rr,cc]);return true}if(color(t)!==col)out.push([rr,cc]);return false};
if(type==='p'){let d=col==='white'?-1:1;if(attackOnly){for(const dc of[-1,1])if(inside(r+d,c+dc))out.push([r+d,c+dc]);return out}if(inside(r+d,c)&&!b[r+d][c]){out.push([r+d,c]);let sr=col==='white'?6:1;if(r===sr&&!b[r+2*d][c])out.push([r+2*d,c])}for(const dc of[-1,1])if(inside(r+d,c+dc)&&b[r+d][c+dc]&&color(b[r+d][c+dc])!==col)out.push([r+d,c+dc]);if(lastMove&&Math.abs(lastMove.fr-lastMove.tr)===2&&lastMove.tr===r&&Math.abs(lastMove.tc-c)===1)out.push([r+d,lastMove.tc]);return out}
if(type==='n'){for(const [dr,dc] of [[2,1],[2,-1],[-2,1],[-2,-1],[1,2],[1,-2],[-1,2],[-1,-2]])add(r+dr,c+dc);return out}
if(type==='k'){for(let dr=-1;dr<=1;dr++)for(let dc=-1;dc<=1;dc++)if(dr||dc)add(r+dr,c+dc);if(!attackOnly)return out}
const dirs=type==='b'?[[1,1],[1,-1],[-1,1],[-1,-1]]:type==='r'?[[1,0],[-1,0],[0,1],[0,-1]]:[[1,1],[1,-1],[-1,1],[-1,-1],[1,0],[-1,0],[0,1],[0,-1]];
for(const [dr,dc] of dirs){let rr=r+dr,cc=c+dc;while(inside(rr,cc)){if(!add(rr,cc))break;rr+=dr;cc+=dc}}return out}
function findKing(b,col){let k=col==='white'?'K':'k';for(let r=0;r<8;r++)for(let c=0;c<8;c++)if(b[r][c]===k)return[r,c];return null}
function attacked(b,r,c,by){for(let rr=0;rr<8;rr++)for(let cc=0;cc<8;cc++)if(b[rr][cc]&&color(b[rr][cc])===by&&pseudoMoves(b,rr,cc,true).some(x=>x[0]===r&&x[1]===c))return true;return false}
function inCheck(b,col){let k=findKing(b,col);return k?attacked(b,k[0],k[1],col==='white'?'black':'white'):true}
function applyMove(b,m){let nb=clone(b),p=nb[m.fr][m.fc];nb[m.tr][m.tc]=p;nb[m.fr][m.fc]=null;if(p.toLowerCase()==='p'&&m.tc!==m.fc&&!b[m.tr][m.tc])nb[m.fr][m.tc]=null;if(p.toLowerCase()==='p'&&m.tr===0||p.toLowerCase()==='p'&&m.tr===7)nb[m.tr][m.tc]=color(p)==='white'?'Q':'q';return nb}
function legalMoves(b,col){let ms=[];for(let r=0;r<8;r++)for(let c=0;c<8;c++)if(b[r][c]&&color(b[r][c])===col){for(const [tr,tc] of pseudoMoves(b,r,c)){let m={fr:r,fc:c,tr,tc};let nb=applyMove(b,m);if(!inCheck(nb,col))ms.push(m)}}return ms}
function render(){const el=$('board');el.innerHTML='';for(let r=0;r<8;r++)for(let c=0;c<8;c++){let s=document.createElement('div');s.className='sq '+((r+c)%2?'dark':'light');s.dataset.r=r;s.dataset.c=c;if(selected&&selected[0]===r&&selected[1]===c)s.classList.add('selected');let p=board[r][c];if(p){let sp=document.createElement('span');sp.className='piece '+color(p);sp.textContent=PIECES[p];s.appendChild(sp)}if(selected&&legalMoves(board,'white').some(m=>m.fr===selected[0]&&m.fc===selected[1]&&m.tr===r&&m.tc===c))s.classList.add(board[r][c]?'capture':'legal');s.onclick=()=>clickSquare(r,c);el.appendChild(s)}$('turnText').textContent=over?'Partie beendet':turn==='white'?'Du bist dran':'Lilou ist am Zug…'}
function clickSquare(r,c){if(over||aiThinking||turn!=='white')return;let p=board[r][c];if(selected){let ms=legalMoves(board,'white').filter(m=>m.fr===selected[0]&&m.fc===selected[1]);let m=ms.find(x=>x.tr===r&&x.tc===c);if(m){makeHuman(m);return}selected=null}if(p&&color(p)==='white')selected=[r,c];render()}
function makeHuman(m){let capture=board[m.tr][m.tc];board=applyMove(board,m);history.push({board:clone(board),last:lastMove});lastMove=m;selected=null;state.coins+=capture?3:1;state.xp+=capture?3:1;if(inCheck(board,'black')){state.coins+=5;state.xp+=5;$('coach').textContent='Schach! 🎉 Sehr gut – du hast deinen Gegner unter Druck gesetzt.'}else $('coach').textContent=tipForMove(m);save();renderStats();render();if(checkEnd('black'))return;turn='black';render();aiThinking=true;setTimeout(aiMove,350)}
function tipForMove(m){const p=board[m.tr][m.tc]?.toLowerCase();return p==='p'?'Tipp: Überlege immer, welche Felder deine Bauern kontrollieren.':'Gut gespielt! Schau vor deinem nächsten Zug: Ist eine deiner Figuren ungedeckt?'}
function evaluate(b){let v={p:100,n:320,b:330,r:500,q:900,k:20000},s=0;for(let r=0;r<8;r++)for(let c=0;c<8;c++)if(b[r][c])s+=(color(b[r][c])==='black'?-1:1)*v[b[r][c].toLowerCase()];return s}
function aiMove(){let ms=legalMoves(board,'black');if(!ms.length){aiThinking=false;checkEnd('black');return}let level=Math.min(4,Math.floor(state.skill/100)+1);let scored=ms.map(m=>{let nb=applyMove(board,m),score=evaluate(nb);if(level>=2){let replies=legalMoves(nb,'white');score-=replies.length*2}if(level>=3&&nb[m.tr][m.tc]?.toLowerCase()==='q')score+=20;return{m,score:score+(Math.random()*160-80)*(level===1?1:level===2?.45:.15)}});scored.sort((a,b)=>a.score-b.score);let pick=scored[0].m;board=applyMove(board,pick);lastMove=pick;turn='white';aiThinking=false;render();checkEnd('white');save()}
function checkEnd(next){let ms=legalMoves(board,next);if(ms.length)return false;over=true;if(inCheck(board,next)){if(next==='black'){state.coins+=20;state.xp+=25;state.skill+=15;$('speech').textContent='Wow, Lilou! Du hast gewonnen! 🏆';$('coach').textContent='Schachmatt! Mega Leistung. Dein Freund wird beim nächsten Mal stärker.'}else{$('speech').textContent='Fast! 🌱 Noch eine Runde?';$('coach').textContent='Du warst nah dran. Schau im Lernbereich noch einmal bei „Schach!“ vorbei.'}}else{$('speech').textContent='Unentschieden! 🤝';$('coach').textContent='Beide haben keinen Zug mehr. Gut durchgehalten!'}state.games++;save();renderStats();return true}
function newGame(){board=START.map(r=>r.map(x=>x||null));selected=null;history=[];turn='white';over=false;aiThinking=false;lastMove=null;$('speech').textContent='Hallo Lilou! ♡ Lust auf eine Partie?';$('coach').textContent='Ziehe eine Figur. Wenn du Hilfe brauchst, findest du Tipps unter „Lernen“.';render()}
$('newGame').onclick=newGame;$('undo').onclick=()=>{if(history.length&&!aiThinking){let h=history[history.length-2];if(h){board=clone(h.board);lastMove=h.last;history=history.slice(0,-2)}else newGame();turn='white';render()}}
const items=[{id:'apple',icon:'🍎',name:'Leckerer Apfel',price:8,desc:'Ein frischer Snack für deinen Freund.'},{id:'cap',icon:'🧢',name:'Lila Käppi',price:35,desc:'Ein cooler neuer Look.'},{id:'crown',icon:'👑',name:'Mini-Krone',price:70,desc:'Für kleine Schachkönige.'},{id:'bow',icon:'🎀',name:'Sternchen-Schleife',price:45,desc:'Funkelt bei jeder Partie.'},{id:'ball',icon:'🏀',name:'Spielball',price:30,desc:'Für eine Pause nach dem Schach.'},{id:'glasses',icon:'🤓',name:'Superbrille',price:55,desc:'Damit sieht dein Freund alles!' }];
function shop(){let g=$('shopGrid');g.innerHTML=items.map(i=>{let owned=state.owned.includes(i.id);return '<article class="shop-item"><div class="item-icon">'+i.icon+'</div><h3>'+i.name+'</h3><p class="muted">'+i.desc+'</p>'+(owned?'<div class="owned">✓ Schon gekauft</div>':'<div class="price">🪙 '+i.price+'</div><button class="primary" onclick="buy(\''+i.id+'\')">Kaufen</button>')+'</article>'}).join('')}
window.buy=id=>{let i=items.find(x=>x.id===id);if(!i||state.owned.includes(id))return;if(state.coins<i.price){$('speech').textContent='Oh! Dafür fehlen noch ein paar Münzen. 💜';return}state.coins-=i.price;state.owned.push(id);$('speech').textContent='Juhu! '+i.name+'! 🎁';save();renderStats();shop()}
$('feed').onclick=()=>{if(state.coins>=8){state.coins-=8;state.heart=Math.min(3,state.heart+1);$('speech').textContent='Mmmh, lecker! Danke, Lilou! 🍎';save();renderStats()}};
$('water').onclick=()=>{if(state.coins>=4){state.coins-=4;state.heart=Math.min(3,state.heart+1);$('speech').textContent='Gluck gluck! 💧';save();renderStats()}};
document.querySelectorAll('.tab').forEach(b=>b.onclick=()=>{document.querySelectorAll('.tab').forEach(x=>x.classList.remove('active'));document.querySelectorAll('.panel').forEach(x=>x.classList.remove('active'));b.classList.add('active');$(b.dataset.tab).classList.add('active');if(b.dataset.tab==='shop')shop()});
renderStats();shop();render();