/* Schach mit Lilou – vollständige, lokale Lernspiel-Logik */
const PIECES={r:'♜',n:'♞',b:'♝',q:'♛',k:'♚',p:'♟',R:'♜',N:'♞',B:'♝',Q:'♛',K:'♚',P:'♟'};
const START=[['r','n','b','q','k','b','n','r'],Array(8).fill('p'),...Array(4).fill(null).map(()=>Array(8).fill(null)),Array(8).fill('P'),['R','N','B','Q','K','B','N','R']];
const KEY='lilouChessV2';
let state=JSON.parse(localStorage.getItem(KEY)||'null')||{coins:30,xp:0,skill:0,heart:3,owned:['starter'],games:0,wins:0};
let board=clone(START),turn='white',selected=null,over=false,aiThinking=false,lastMove=null,history=[],notation=[];
const $=id=>document.getElementById(id), clone=b=>b.map(r=>r.slice()), color=p=>p&&p===p.toUpperCase()?'white':'black';
function save(){localStorage.setItem(KEY,JSON.stringify(state))}
function inside(r,c){return r>=0&&r<8&&c>=0&&c<8}
function findKing(b,col){const k=col==='white'?'K':'k';for(let r=0;r<8;r++)for(let c=0;c<8;c++)if(b[r][c]===k)return[r,c];return null}
function pseudo(b,r,c,attackOnly=false){const p=b[r][c];if(!p)return[];const col=color(p),t=p.toLowerCase(),out=[];const add=(rr,cc)=>{if(!inside(rr,cc))return false;const x=b[rr][cc];if(!x){out.push([rr,cc]);return true}if(color(x)!==col)out.push([rr,cc]);return false};
if(t==='p'){const d=col==='white'?-1:1;if(attackOnly){for(const dc of[-1,1])if(inside(r+d,c+dc))out.push([r+d,c+dc]);return out}if(inside(r+d,c)&&!b[r+d][c]){out.push([r+d,c]);const sr=col==='white'?6:1;if(r===sr&&!b[r+2*d][c])out.push([r+2*d,c])}for(const dc of[-1,1])if(inside(r+d,c+dc)&&b[r+d][c+dc]&&color(b[r+d][c+dc])!==col)out.push([r+d,c+dc]);if(lastMove&&lastMove.piece?.toLowerCase()==='p'&&Math.abs(lastMove.fr-lastMove.tr)===2&&lastMove.tr===r&&Math.abs(lastMove.tc-c)===1)out.push([r+d,lastMove.tc]);return out}
if(t==='n'){for(const x of[[2,1],[2,-1],[-2,1],[-2,-1],[1,2],[1,-2],[-1,2],[-1,-2]])add(r+x[0],c+x[1]);return out}
if(t==='k'){for(let dr=-1;dr<=1;dr++)for(let dc=-1;dc<=1;dc++)if(dr||dc)add(r+dr,c+dc);return out}
const dirs=t==='b'?[[1,1],[1,-1],[-1,1],[-1,-1]]:t==='r'?[[1,0],[-1,0],[0,1],[0,-1]]:[[1,1],[1,-1],[-1,1],[-1,-1],[1,0],[-1,0],[0,1],[0,-1]];
for(const d of dirs){let rr=r+d[0],cc=c+d[1];while(inside(rr,cc)){if(!add(rr,cc))break;rr+=d[0];cc+=d[1]}}return out}
function attacked(b,r,c,by){for(let rr=0;rr<8;rr++)for(let cc=0;cc<8;cc++)if(b[rr][cc]&&color(b[rr][cc])===by&&pseudo(b,rr,cc,true).some(x=>x[0]===r&&x[1]===c))return true;return false}
function inCheck(b,col){const k=findKing(b,col);return !k||attacked(b,k[0],k[1],col==='white'?'black':'white')}
function rightsAfter(m,p){return m}
function apply(b,m){const n=clone(b),p=n[m.fr][m.fc];n[m.fr][m.fc]=null;n[m.tr][m.tc]=p;
if(m.enPassant)n[m.fr][m.tc]=null;
if(p.toLowerCase()==='k'&&Math.abs(m.tc-m.fc)===2){const rookC=m.tc>m.fc?7:0,rookTo=m.tc>m.fc?5:3;n[m.tr][rookTo]=n[m.tr][rookC];n[m.tr][rookC]=null}
if(p.toLowerCase()==='p'&&(m.tr===0||m.tr===7))n[m.tr][m.tc]=color(p)==='white'?'Q':'q';
return n}
function stateRights(){return state.rights||{K:true,Q:true,k:true,q:true}}
function legal(b,col,rights=stateRights(),lm=lastMove){let out=[];for(let r=0;r<8;r++)for(let c=0;c<8;c++){if(!b[r][c]||color(b[r][c])!==col)continue;for(const [tr,tc] of pseudo(b,r,c)){const m={fr:r,fc:c,tr,tc,piece:b[r][c]};if(b[tr][tc]?.toLowerCase()==='k')continue;if(b[r][c].toLowerCase()==='p'&&tc!==c&&!b[tr][tc])m.enPassant=!!lm&&lm.piece?.toLowerCase()==='p'&&Math.abs(lm.fr-lm.tr)===2&&lm.tr===r&&lm.tc===tc;
let nb=apply(b,m);if(!inCheck(nb,col))out.push(m)}}
const k=findKing(b,col);if(k&&!inCheck(b,col)){const row=col==='white'?7:0;const opp=col==='white'?'black':'white';if(k[0]===row&&k[1]===4){
for(const side of ['K','Q']){if(!rights[side==='K'?'K':'Q'])continue;const rookC=side==='K'?7:0,between=side==='K'?[5,6]:[1,2,3];if(b[row][rookC]=== (col==='white'?'R':'r')&&between.every(c=>!b[row][c])&&![4,...(side==='K'?[5,6]:[3,2])].some(c=>attacked(b,row,c,opp))){out.push({fr:row,fc:4,tr:row,tc:side==='K'?6:2,piece:col==='white'?'K':'k',castle:side})}}
}}return out}
function moveName(m,before){const p=m.piece.toUpperCase();if(m.castle)return m.castle==='K'?'O-O':'O-O-O';const files='abcdefgh';return (p==='P'?'':p)+(m.fc!==m.tc&&p==='P'?files[m.fc]:'')+(before[m.tr][m.tc]||m.enPassant?'x':'')+files[m.tc]+(8-m.tr)}
function updateRights(m,p){if(p==='K')state.rights.K=state.rights.Q=false;if(p==='k')state.rights.k=state.rights.q=false;if(p==='R'&&m.fr===7&&m.fc===0)state.rights.Q=false;if(p==='R'&&m.fr===7&&m.fc===7)state.rights.K=false;if(p==='r'&&m.fr===0&&m.fc===0)state.rights.q=false;if(p==='r'&&m.fr===0&&m.fc===7)state.rights.k=false;if(m.tr===7&&m.tc===0)state.rights.Q=false;if(m.tr===7&&m.tc===7)state.rights.K=false;if(m.tr===0&&m.tc===0)state.rights.q=false;if(m.tr===0&&m.tc===7)state.rights.k=false}
function makeMove(m){const before=clone(board),p=board[m.fr][m.fc],cap=board[m.tr][m.tc];history.push({board:clone(board),turn,rights:{...stateRights()},lastMove:lastMove,notation:notation.slice(),state:{coins:state.coins,xp:state.xp,skill:state.skill,wins:state.wins,games:state.games}});
updateRights(m,p);board=apply(board,m);lastMove={...m};notation.push(moveName(m,before));state.coins+=cap?3:1;state.xp+=cap?3:1;if(inCheck(board,turn==='white'?'black':'white')){state.coins+=5;state.xp+=5;$('coach').textContent='Schach! ✨ Du hast einen starken Moment gefunden.'}save();renderStats();render();return cap}
function makeHuman(m){if(aiThinking||over)return;makeMove(m);selected=null;if(endFor('black'))return;turn='black';render();aiThinking=true;setTimeout(aiMove,300)}
function evaluate(b){const val={p:100,n:320,b:330,r:500,q:900,k:20000};let s=0;for(let r=0;r<8;r++)for(let c=0;c<8;c++)if(b[r][c]){let v=val[b[r][c].toLowerCase()];s+=(color(b[r][c])==='black'?-v:v);if(r>1&&r<6)s+=(color(b[r][c])==='black'?-1:1)*3}return s}
function minimax(b,depth,alpha,beta,maximizing,rights,last){if(depth===0)return evaluate(b);const col=maximizing?'black':'white',ms=legal(b,col,rights,last);if(!ms.length)return inCheck(b,col)?(maximizing?-999999:999999):0;let best=maximizing?-Infinity:Infinity;for(const m of ms){const nr={...rights};const p=b[m.fr][m.fc];if(p.toLowerCase()==='k'){if(color(p)==='black')nr.k=nr.q=false;else nr.K=nr.Q=false}const v=minimax(apply(b,m),depth-1,alpha,beta,!maximizing,nr,m);if(maximizing){best=Math.max(best,v);alpha=Math.max(alpha,v)}else{best=Math.min(best,v);beta=Math.min(beta,v)}if(beta<=alpha)break}return best}
function aiMove(){if(over)return;const level=Math.min(4,Math.floor(state.skill/100)+1),depth=level>=4?3:level>=2?2:1,ms=legal(board,'black');if(!ms.length){aiThinking=false;endFor('black');return}
let choices=ms.map(m=>{const nr={...stateRights()};const v=minimax(apply(board,m),Math.max(0,depth-1),-Infinity,Infinity,false,nr,m);return{m,v:v+(Math.random()*30-15)*(level===1?3:level===2?1:.2)}}).sort((a,b)=>b.v-a.v);
const pick=choices[Math.floor(Math.random()*Math.min(level===1?Math.min(4,choices.length):level===2?Math.min(2,choices.length):1,choices.length))].m;
makeMove(pick);turn='white';aiThinking=false;render();endFor('white');save()}
function endFor(col){const ms=legal(board,col);if(ms.length)return false;over=true;if(inCheck(board,col)){if(col==='black'){state.wins++;state.skill+=15;state.coins+=20;state.xp+=25;$('speech').textContent='Lilou, Schachmatt! 🏆';$('coach').textContent='Du hast gewonnen! Dein Freund lernt dazu und wird beim nächsten Mal stärker.'}else{$('speech').textContent='Fast geschafft! 🌱';$('coach').textContent='Dieses Mal hat dein Freund gewonnen. Schau, was du beim nächsten Mal anders machen kannst.'}}else{$('speech').textContent='Unentschieden! 🤝';$('coach').textContent='Eine Remis-Partie! Das war richtig konzentriert.'}state.games++;save();renderStats();return true}
function clickSquare(r,c){if(over||aiThinking||turn!=='white')return;const p=board[r][c];if(selected){const m=legal(board,'white').find(x=>x.fr===selected[0]&&x.fc===selected[1]&&x.tr===r&&x.tc===c);if(m){makeHuman(m);return}selected=null}if(p&&color(p)==='white')selected=[r,c];render()}
function render(){const el=$('board');el.innerHTML='';const ms=selected?legal(board,'white').filter(m=>m.fr===selected[0]&&m.fc===selected[1]):[];for(let r=0;r<8;r++)for(let c=0;c<8;c++){const s=document.createElement('div');s.className='sq '+((r+c)%2?'dark':'light');if(selected?.[0]===r&&selected?.[1]===c)s.classList.add('selected');const p=board[r][c];if(p){const sp=document.createElement('span');sp.className='piece '+color(p);sp.textContent=PIECES[p];s.appendChild(sp)}if(ms.some(m=>m.tr===r&&m.tc===c))s.classList.add(p?'capture':'legal');s.onclick=()=>clickSquare(r,c);el.appendChild(s)}$('turnText').textContent=over?'Partie beendet':turn==='white'?'Du bist dran':'Lilous Freund denkt nach…';renderMoves()}
function renderMoves(){const e=$('moves');if(!notation.length){e.textContent='Noch keine Züge';return}e.innerHTML=notation.map((n,i)=>i%2===0?'<div class="move-row"><span class="move-no">'+(i/2+1)+'.</span><span class="move-human">'+n+'</span>': '<span class="move-ai">'+n+'</span></div>').join('')}
function renderStats(){const lvl=Math.floor(state.skill/100)+1,names=['Anfänger','Entdecker','Taktik-Fan','Schach-Profi','Meister'];$('coins').textContent=state.coins;$('xp').textContent=state.xp;$('level').textContent=lvl;$('shopCoins').textContent=state.coins;$('skill').textContent=names[Math.min(4,lvl-1)];$('skillbar').style.width=Math.max(5,state.skill%100)+'%';$('difficultyText').textContent='Gegner-Stufe '+Math.min(4,lvl)+' · '+(lvl<2?'freundlich und entspannt':lvl<3?'achtet schon auf deine Figuren':lvl<4?'plant kleine Taktiken':'denkt mehrere Züge voraus');$('hearts').textContent='♥ '.repeat(state.heart).trim()+' ♡ '.repeat(3-state.heart).trim();$('friendMood').textContent=state.heart===3?'Dein Freund fühlt sich pudelwohl!':state.heart===2?'Ein kleiner Snack wäre schön.':'Zeit für Wasser und eine Pause!';setAccessory()}
function setAccessory(){const ids=['cap','crown','bow','glasses','ball'];const found=ids.find(id=>state.owned.includes(id));for(const id of ids)$('heroAccessory')?.classList.remove(id);if(found)$('heroAccessory')?.classList.add(found)}
function newGame(){board=clone(START);turn='white';selected=null;over=false;aiThinking=false;lastMove=null;notation=[];history=[];state.rights={K:true,Q:true,k:true,q:true};$('speech').textContent='Hallo Lilou! ♡ Lust auf eine Partie?';$('coach').textContent='Erst schauen, dann ziehen. Welche Figur möchtest du bewegen?';save();render()}
$('newGame').onclick=newGame;
$('undo').onclick=()=>{if(aiThinking||!history.length)return;const h=history.length>=2?history[history.length-2]:history[0];board=clone(h.board);turn='white';state.rights={...h.rights};lastMove=h.lastMove;notation=h.notation.slice();const st=h.state;Object.assign(state,st);history=history.slice(0,Math.max(0,history.length-2));over=false;save();renderStats();render();$('coach').textContent='Zug zurück! Überlege in Ruhe noch einmal.'};
const items=[{id:'apple',icon:'🍎',name:'Leckerer Apfel',price:8,desc:'Ein frischer Snack.'},{id:'cap',icon:'🧢',name:'Lila Käppi',price:35,desc:'Ein cooler Look.'},{id:'crown',icon:'👑',name:'Mini-Krone',price:70,desc:'Für einen kleinen Champion.'},{id:'bow',icon:'🎀',name:'Sternchen-Schleife',price:45,desc:'Funkelt bei jeder Partie.'},{id:'ball',icon:'🏀',name:'Spielball',price:30,desc:'Für die Pause.'},{id:'glasses',icon:'🤓',name:'Superbrille',price:55,desc:'Damit sieht dein Freund alles.'}];
function shop(){const g=$('shopGrid');g.innerHTML=items.map(i=>state.owned.includes(i.id)?'<article class="shop-item"><div class="item-icon">'+i.icon+'</div><h3>'+i.name+'</h3><p class="muted">'+i.desc+'</p><div class="owned">✓ Schon gekauft</div></article>':'<article class="shop-item"><div class="item-icon">'+i.icon+'</div><h3>'+i.name+'</h3><p class="muted">'+i.desc+'</p><div class="price">🪙 '+i.price+'</div><button class="primary" onclick="buy(\''+i.id+'\')">Kaufen</button></article>').join('')}
window.buy=id=>{const i=items.find(x=>x.id===id);if(!i||state.owned.includes(id))return;if(state.coins<i.price){$('speech').textContent='Noch ein paar Münzen sammeln, dann klappt es! 💜';return}state.coins-=i.price;state.owned.push(id);$('speech').textContent='Juhu! '+i.name+' ist da! 🎁';save();renderStats();shop()};
$('feed').onclick=()=>{if(state.coins>=8){state.coins-=8;state.heart=Math.min(3,state.heart+1);$('speech').textContent='Mmmh, lecker! 🍎';save();renderStats()}};
$('water').onclick=()=>{if(state.coins>=4){state.coins-=4;state.heart=Math.min(3,state.heart+1);$('speech').textContent='Gluck gluck! 💧';save();renderStats()}};
document.querySelectorAll('.tab').forEach(b=>b.onclick=()=>{document.querySelectorAll('.tab').forEach(x=>x.classList.remove('active'));document.querySelectorAll('.panel').forEach(x=>x.classList.remove('active'));b.classList.add('active');$(b.dataset.tab).classList.add('active');if(b.dataset.tab==='shop')shop()});
if(!state.rights)state.rights={K:true,Q:true,k:true,q:true};
renderStats();shop();render();